// app/components/ui/button.tsx
import * as React from "react"
import { Slot } from "@radix-ui/react-slot"
import { cva, type VariantProps } from "class-variance-authority"

import { cn } from "~/lib/utils"

const buttonVariants = cva(
  "inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:size-4 [&_svg]:shrink-0",
  {
    variants: {
      variant: {
        default: "bg-primary text-primary-foreground shadow hover:bg-primary/90",
        destructive: "bg-destructive text-destructive-foreground shadow-sm hover:bg-destructive/90",
        outline:
          "border border-input bg-background shadow-sm hover:bg-accent hover:text-accent-foreground",
        secondary: "bg-secondary text-secondary-foreground shadow-sm hover:bg-secondary/80",
        ghost: "hover:bg-accent hover:text-accent-foreground",
        link: "text-primary underline-offset-4 hover:underline",
      },
      size: {
        default: "h-9 px-4 py-2",
        sm: "h-8 rounded-md px-3 text-xs",
        lg: "h-10 rounded-md px-8",
        icon: "h-9 w-9",
      },
    },
    defaultVariants: {
      variant: "default",
      size: "default",
    },
  }
)

export interface ButtonProps
  extends React.ButtonHTMLAttributes<HTMLButtonElement>,
    VariantProps<typeof buttonVariants> {
  asChild?: boolean
}

const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
  ({ className, variant, size, asChild = false, ...props }, ref) => {
    const Comp = asChild ? Slot : "button"
    return (
      <Comp className={cn(buttonVariants({ variant, size, className }))} ref={ref} {...props} />
    )
  }
)
Button.displayName = "Button"

export { Button, buttonVariants }

// apps/frontend/src/lib/components/ui/Button.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'

  let {
    variant = 'secondary',
    size = 'md',
    href = undefined,
    disabled = false,
    type = 'button',
    children,
    onclick,
    ...rest
  }: {
    variant?: 'primary' | 'secondary' | 'ghost'
    size?: 'sm' | 'md'
    href?: string
    disabled?: boolean
    type?: 'button' | 'submit' | 'reset'
    children?: Snippet
    onclick?: () => void
    [key: string]: any
  } = $props()
</script>

{#if href}
  <a {href} class="btn btn--{variant} btn--{size}" {...rest}>
    {@render children?.()}
  </a>
{:else}
  <button {type} {disabled} {onclick} class="btn btn--{variant} btn--{size}" {...rest}>
    {@render children?.()}
  </button>
{/if}

<style>
  .btn {
    display: inline-flex;
    align-items: center;
    gap: var(--space-2);
    font-family: var(--font-sans);
    font-weight: 500;
    border-radius: var(--radius-full);
    transition: all var(--duration) var(--ease);
    white-space: nowrap;
    text-decoration: none;
    border: 0.5px solid transparent;
  }

  .btn:disabled {
    opacity: 0.5;
    pointer-events: none;
  }

  /* Sizes */
  .btn--sm {
    font-size: 12px;
    padding: 5px 14px;
  }

  .btn--md {
    font-size: 13px;
    padding: 8px 20px;
  }

  /* Variants */
  .btn--primary {
    background: var(--color-accent);
    color: #fff;
    border-color: var(--color-accent);
  }

  .btn--primary:hover {
    background: var(--color-accent-hover);
    border-color: var(--color-accent-hover);
  }

  .btn--secondary {
    background: var(--color-bg-secondary);
    color: var(--color-text);
    border-color: var(--color-border);
  }

  .btn--secondary:hover {
    border-color: var(--color-border-hover);
  }

  .btn--ghost {
    background: transparent;
    color: var(--color-text-2);
    border-color: transparent;
  }

  .btn--ghost:hover {
    background: var(--color-bg-secondary);
    color: var(--color-text);
  }
</style>
